config/routes.rb
Rails.application.routes.draw do

  resources :channels
  resources :videos
  resources :grades do
    resources :disciplines, only: [:create, :show]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grade.rb
class Grade < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :users
  has_many :disciplines

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

  before_action :set_grade, only: [:show, :edit, :update]

  def show
    @disciplines = Discipline.where(grade: @grade)
    @discipline = Discipline.new

  end

  def index
    @grades = policy_scope(Grade)
  end

  def new
    @grade = Grade.new
    authorize @grade
  end

  def create
    @grade = Grade.new(grade_params)
    authorize @grade
    if @grade.save
      redirect_to @grade, notice: 'Grade was successfully created.'
    else
      render :new
    end
  end

  def update
    if @grade.update(grade_params)
      render :show, status: :ok, location: @grade
    else
      render :edit
    end
  end

  private

  def set_grade
    @grade = Grade.find(params['id'])
    authorize @grade
  end

  def grade_params
    params.require(:grade).permit(:name)
  end

end

app/views/grades/edit.html.erb
<h2>Edit Grade</h2>

<%= simple_form_for(@grade) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<% @grades.each do |grade| %>
  <%= link_to grade do %>
    <p><%= grade.name %></p>
  <% end %>
<% end %>

app/views/grades/new.html.erb
<h2>New Grade</h2>

<%= simple_form_for(@grade) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<h2><%= @grade.name %></h2>
<% @disciplines.each do |discipline| %>
  <p><%= link_to discipline.name, grade_discipline_path(@grade, discipline) %></p>

<% end %>

<%= render 'disciplines/form', grade: @grade, discipline: @discipline %>

<p>
  <% if current_user %>
    <%= link_to "Edit", edit_grade_path(@grade) if policy(@grade).edit? %>

  <% end %>
  <%= link_to "Back", grades_path %>
</p>