config/routes.rb
Rails.application.routes.draw do

  resources :channels
  resources :videos
  resources :grades do
    resources :disciplines, only: [:create, :show]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord

  validates :yt_id, :name, presence: true
  validates :yt_id, :name, uniqueness: true
  validates :yt_id, format: { with: /.{24}/,
                           message: "Please try a valid channel id" }

  belongs_to :user
  has_many :videos, dependent: :destroy

  # def self.from_yt(yt_id)
  # # Either create a User record or update it based on the provider (Google) and the UID
  #   where(yt_id: yt_id).first_or_create do |channel|
  #     yt_channel = Yt::Channel.new id: channel.yt_id
  #     channel.name = yt_channel.title
  #     channel.description = yt_channel.description
  #     channel.thumbnail_url = yt_channel.thumbnail_url
  #     channel.published_at = yt_channel.published_at
  #   end
  # end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  def show
    @videos = Video.where(channel: @channel)
  end

  def index
    @channels = policy_scope(Channel)
  end

  def new
    @channel = Channel.new
    authorize @channel
  end

  def create
    @channel = Channel.new(new_channel_params)
    authorize @channel
    yt_channel = Yt::Channel.new id: @channel.yt_id
    if yt_channel.snippets.any?
      @channel.name = yt_channel.title
      @channel.description = yt_channel.description
      @channel.thumbnail_url = yt_channel.thumbnail_url
      @channel.published_at = yt_channel.published_at
    else
      return render :new, notice: "Channel's id isn't valid."
    end

    @channel.user = current_user

    if @channel.save
      redirect_to @channel, notice: 'Channel was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @channel.update(edit_channel_params)
      render :show, status: :ok, location: @channel
    else
      render :edit
    end
  end

  def destroy
    @channel.destroy
    redirect_to channels_url, notice: 'Channel was successfully destroyed.'
  end

  private

  def set_channel
    @channel = Channel.find(params['id'])
    authorize @channel
  end

  def new_channel_params
    params.require(:channel).permit(:yt_id)
  end

  def edit_channel_params
    params.require(:channel).permit(:public, :description)
  end

end

app/views/channels/_form.html.erb
<%= simple_form_for(@channel) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :yt_id %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h2>New Channel</h2>

<%= simple_form_for(@channel) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :yt_id %>
    <%= f.input :user %>
    <%= f.input :public %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<ul>
  <% @channels.each do |channel| %>
    <li><%= link_to "#{channel.id} => #{channel.name} by #{channel.user.email}", channel_path(channel) %>
      <% if current_user %>
        <% if policy(channel).edit? %>
        | Edit this "channel" by clicking <%= link_to "here", edit_channel_path(channel) %>
        <% end %>
        <% if policy(channel).destroy? %>
        <%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if current_user %>
  <% if policy(Channel).new? %>
    <p>add a "channel" by clicking <%= link_to "here", new_channel_path %></p>
  <% end %>
<% end %>

<p><%= link_to "Back", root_path %></p>

app/views/channels/new.html.erb
<h2>New Channel</h2>

<%= simple_form_for(@channel) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :yt_id %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<h2><%= @channel.name %></h2>
<% @videos.each do |video| %>
<p><%= image_tag video.thumbnail_url, height: "100px" %> => <%= video.name %> / id : <%= video.yt_id %></p>
<% end %>

<p>
  <% if current_user %>
    <%= link_to "Edit", edit_channel_path(@channel) if policy(@channel).edit? %>

  <% end %>
  <%= link_to "Back", channels_path %>
</p>