config/routes.rb
Rails.application.routes.draw do

  resources :channels
  resources :videos
  resources :grades do
    resources :disciplines, only: [:create, :show]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord

  validates :yt_id, :name, presence: true
  validates :yt_id, uniqueness: true

  belongs_to :channel
  has_many :video_topics
  has_many :topics, through: :video_topics

    def self.from_yt(yt_id)
   # Either create a User record or update it based on the provider (Google) and the UID
    where(yt_id: yt_id).first_or_create do |video|
      yt_video = Yt::Video.new id: video.yt_id
      video.name = yt_video.title
      video.description = yt_video.description
      video.thumbnail_url = yt_video.thumbnail_url
      video.duration = yt_video.duration
      video.captioned = yt_video.captioned?
      video.published_at = yt_video.published_at

      # raise
   end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_video, only: [:show, :edit, :update]


  def show
  end

  def index
    @videos = policy_scope(Video)
  end

  def new
    @video = Video.new
    authorize @video
  end

  def create
    @video = Video.new(new_video_params)
    authorize @video
    yt_video = Yt::Video.new id: @video.yt_id
    if yt_video.snippets.any? && Channel.exists?(yt_id: yt_video.channel_id)
      @video.name = yt_video.title
      @video.channel = Channel.find_by(yt_id: yt_video.channel_id)
      @video.description = yt_video.description
      @video.thumbnail_url = yt_video.thumbnail_url
      @video.duration = yt_video.duration
      @video.captioned = yt_video.captioned?
      @video.published_at = yt_video.published_at
    else
      return render :new, notice: "Video's id isn't valid."
    end

    if @video.save
      redirect_to @video, notice: 'Video was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @video.update(edit_video_params)
      render :show, status: :ok, location: @video
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_url, notice: 'Video was successfully destroyed.'
  end

  private

  def set_video
    @video = Video.find(params['id'])
    authorize @video
  end

  def new_video_params
    params.require(:video).permit(:yt_id)
  end

  def edit_video_params
    params.require(:video).permit(:public, :description)
  end

end

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :yt_id %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h2>Edit Video</h2>

<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :yt_id %>
    <%= f.input :channel %>
    <%= f.input :public %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<ul>
  <% @videos.each do |video| %>
    <li><%= link_to "#{video.id} => #{video.name} by #{video.channel.user.email}", video_path(video) %>
      <% if current_user %>
        <% if policy(video).edit? %>
        | Edit this "video" by clicking <%= link_to "here", edit_video_path(video) %>
        <% end %>
        <% if policy(video).destroy? %>
        <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if current_user %>
  <% if policy(@videos).new? %>
    <p>add a "video" by clicking <%= link_to "here", new_video_path %></p>
  <% end %>
<% end %>

<p><%= link_to "Back", root_path %></p>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<h2><%= @video.name %></h2>
<p><%= image_tag @video.thumbnail_url, height: "100px" %> => <%= @video.name %> / id : <%= @video.yt_id %></p>

<p>
  <% if current_user %>
    <%= link_to "Edit", edit_video_path(@video) if policy(@video).edit? %>

  <% end %>
  <%= link_to "Back", videos_path %>
</p>